### ISSUE TITLE
'An error ocurred'

### ISSUE THREAD

**Issue by Tomxyttt** [x753/Lethal-Company-Mimics#10]
Well, i downloaded the mod, when i hosted a game my friends couldnt join, and i tried joining any random party but it didnt woked, so... i dont know what to do

**Comment by x753** [comment]
Everyone needs the mod installed to play together.

**Comment by tanyan-tanyan** [comment]
> Everyone needs the mod installed to play together.

Question - If I have Mimics installed but the host doesn't, will I be able to join them to simply play without the mimics?
I have a little r2modman profile with (I assume) only client-side things and I slapped Mimics on, to be able to join public BL servers that include the mimic mod in their name. This is not something every public server does, but I've been getting the "An error occurred" message for like 80% of the public BL servers I attempt to join. Could you clarify if the Mimics causes this limitation?

If the answer is yes, would it be possible to make it so the player can still join modded servers that don't have the Mimics mod, even if the joining player does? I hope you understand, it's been a pain trying to find servers when most of them refuse you and there's no way to find out why.

**Comment by x753** [comment]
Mimics registers a networked prefab, and it seems lobbies reject you if you don't have the same list of networked prefabs. I don't know how to get around this, so unless I get a PR it will remain this way.
