### ISSUE TITLE
Mimic have no difference

### ISSUE THREAD

**Issue by Konichuchu** [x753/Lethal-Company-Mimics#12]
Hey, I just spent 4 hours playing (with default config) and the mimic had 0 difference with actual fire exit.
Maybe it was the color (I have a few problems to distinguish between some shades of colors) but it is quite strange for having only color difference in 4hours of playing 

I think I know all the things that can be seen to check : 

<details>
  <summary>Spoiler warning</summary>

  - The hover & hold with "FEED" 
  
  - The hold DIE 
  
  - The middle finger 
  
  - The spray to trigger the noise 

  - The shovel to trigger the noise 

</details>

I played in V45 with this profile : 018c7962-d7ab-e145-6ea4-cad7eb300b12

**Comment by x753** [comment]
The imperfections only appear in easy mode. By default, the only ways to tell are through items or cooperation with your team.
