### ISSUE TITLE
mimic has no difference (with easy + colorblind modes on)

### ISSUE THREAD

**Issue by FirewallDaProtogen** [x753/Lethal-Company-Mimics#13]
i was playing with colorblind mode and easy mode enabled, and noticed that for some reason mimics dont have any difference!
can also make video if required to further show.

![doors](https://github.com/x753/Lethal-Company-Mimics/assets/113303660/a6ede8a8-a8f6-4b9f-b497-8830125011be)

**Comment by x753** [comment]
There is a difference. Interact with it.

**Comment by FirewallDaProtogen** [comment]
there is no difference, even when interacting

the only difference is that i die, but thats not exactly something that can be told beforehand

**Comment by Cebraxo** [comment]
Most (not cooperative and immature) helpful mod dev ever.
