### ISSUE TITLE
The door doesn't respond

### ISSUE THREAD

**Issue by IhorMongov** [x753/Lethal-Company-Mimics#20]
The mod doesn't work correctly. To be exact, the door itself will spawn, but you cannot interact with it. When attempting to interact, be it hitting with a shovel or opening, nothing happens. The interaction scale when opening the door reaches the end and suddenly ends. I suspect a conflict with other mods, but I don't understand what exactly.

Does the presence of other interior maps affect the operation of the mod, even if its spawn location is a vanilla map?

I'll attach [ModList.txt](https://github.com/x753/Lethal-Company-Mimics/files/14972183/ModList.txt). "+" means that the mod is active in the assembly, "-" that the mod has been removed for one or another reason.
Sorry for my bad English. :D

**Comment by x753** [comment]
What version of the game are you on? It was just updated to v50, so there are a ton of mods that could have caused the issue. I've had no issues with the mod myself on v50, so I can only believe it's a conflict.

**Comment by IhorMongov** [comment]
At the moment I'm still playing on v49, and I'm also inclined to believe that this is a conflict. I just tested the door without mods that add moons and interiors, and it still doesn't work. So, I continue my search further.

**Comment by x753** [comment]
If you want to play on an older version of the game, you'll need to use a version of Mimics before v2.5.0
