### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by xXShepardXx** [x753/Lethal-Company-Mimics#24]
Hi, would it be possible to add for example:

 -mimic doors sometimes say "FRIE EXIT" or "FIRE EIXT"
 -crooked letters
 -lower handlebar

I find it very hard to find out to tell a difference even when there are mimic and real door side by side, and without a shovel its a real hit or miss for me. Also the flip off cursor only shows after hitting the door with shovel and I think that makes it silly but also redundant how about the fake door will flip out sometimes regardless of being hit. 

another idea I have:
-if you use a flashlight on a mimic it will show some scratches/blood/marks on different parts like sometimes on a handle sometimes on the light above the door and sometimes on door, maybe letters, it would only work if you get really close to inspect it, but shine the light for too long and it will get pissed and auto chomp you, no sound que.

**Comment by x753** [comment]
I don't have any plans on returning to the "imperfection" system that existed in prior versions. After a lot of playtesting, any sort of distinguishable difference that doesn't require equipment makes them entirely non-threatening once you figure it out. The middle finger cursor is intended to protect you from situations where someone else already angered the mimic with a shovel, but you weren't around to hear the growl.

Flashlights are probably too cheap to use as a mimic tester. I want to encourage using some of the other equipment like spray paint or lockpickers.
