### ISSUE TITLE
Mimic interrupts ship for takeoff.

### ISSUE THREAD

**Issue by Zekrodiak** [x753/Lethal-Company-Mimics#3]
The Mimic mod doesn't let me use the lever to take off after I land on any moon (stays on waiting for ship to land). plus when the timer hits 12:00am, the ship doesn't take of either.

**Comment by x753** [comment]
I don't think this is an issue with the mimic mod, it's likely another mod you have installed.

**Comment by Zekrodiak** [comment]
yeah just noticed, i was about to delete the post, my bad XD
