### ISSUE TITLE
Mimic not visible for all players.

### ISSUE THREAD

**Issue by GreerL0319** [x753/Lethal-Company-Mimics#4]
Some of my group can see and use it, but some just see an outline where one should be. We are all on the same version.

**Comment by x753** [comment]
Someone probably installed it wrong or doesn't have the config file. Make sure everyone has the same mod, same version, and same config files. I recommend generating a profile code with the mod manager to sync things properly with your group.

**Comment by GreerL0319** [comment]
okay, the problem is that we dont have the same config files, i figured it was server sided with the host
