### ISSUE TITLE
ways to tell out fake doors?

### ISSUE THREAD

**Issue by Adney467** [x753/Lethal-Company-Mimics#5]
how do you tell if the door is fake or not? what possible imperfection would it have?

**Comment by VenoPhage** [comment]
There appears to be absolutely no way to tell, had a real one and fake one next to each other and they were identical

**Comment by Cubly** [comment]
They can say 'Feed' instead of 'Exit' when hovering.
They can say 'DIE' instead of 'Exit' when hovering (also the interaction is quicker).
They can have a fingerless hand icon when hovering.
They can take slightly longer to exit from.
They can be a different colour.
The light above it can be a different colour.

**Comment by VenoPhage** [comment]
Not a fan of the hud being different tbh, is there a config to change what differences there can be cause yea hud things isn't something anyone is gonna think about without knowing

**Comment by Cubly** [comment]
> Not a fan of the hud being different tbh, is there a config to change what differences there can be cause yea hud things isn't something anyone is gonna think about without knowing

If you set the difficulty level to 2, you will only get the colour changes. No option to specifically choose which imperfections you want. 

I do have to say though the novelty of them wears off after you know what to look for, it just becomes a case of checking a fire exit once you come across it. I'm not sure what else could be changed though to give them 'replay' value. I suppose in a panic you could forget and use the incorrect door.

**Comment by x753** [comment]
I'm in the process of figuring out a way to balance them so that it isn't just knowing how or not knowing how. For now though I'm happy enough that some people think it's too easy and some think it's impossible.
