### ISSUE TITLE
"Slightly off-color door" tell presents an accessibility issue for people with low vision/color blindness. 

### ISSUE THREAD

**Issue by phoenix492** [x753/Lethal-Company-Mimics#8]
See title. There's not really any recourse on the user side than just disabling it in config, but the fact that the defaults come loaded with accessibility issues is less than optimal.

**Comment by x753** [comment]
I don't believe color blindness was ever an issue, but regardless as of v2.0.0 the imperfection system has been removed so this should no longer be an issue.
