### ISSUE TITLE
No distinction between a mimic and a regular door in 2.0.0

### ISSUE THREAD

**Issue by AndrewEllen** [x753/Lethal-Company-Mimics#9]
Am I blind or is there no distinction. I set the difficulty to 1 (the easiest) and I can't for the life of me figure it out. I've had two side by side doors and it comes down to a coin toss

**Comment by x753** [comment]
As of v2.0.0 difficulty levels no longer exist. The visual differences between the two are too difficult for even me to spot, so I recommend trying to figure out which is real through other methods. Try out different equipment and tactics!

An easy mode will be coming in v2.1.0 which will bring add a config option to make more obvious imperfections for mimics.
